name: Build macOS Tauri

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      run: actions/checkout@v3
      
    - name: Install dependencies
      run: npm install

    - name: Build desktop app
      run: npm run build --workspace=app

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v3
      with:
          name: macOS-installer
          path: src-tauri/target/release/bundle/dmg/
